name: Deploy

on:
  push:
    branches:
      - develop
      - release
      - main
  repository_dispatch:

env:
  CI: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: contentful
        if: github.event.client_payload
        env:
          ENVCODE: prd
        run:
          echo {{ENVCODE}}
      
      - name: チェックアウト
        if: github.event_name == 'push'
        uses: actions/checkout@v2
      
      - name: dispatchチェックアウト
        if: github.event_name == 'repository_dispatch'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
